name: Build Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download and set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Download and set up NDK
      run: |
        echo "::group::Download NDK"
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux-x86_64.zip
        unzip android-ndk-r23b-linux-x86_64.zip -d $HOME
        echo "::endgroup::"
        echo "NDK_HOME=$HOME/android-ndk-r23b" >> $GITHUB_ENV

    - name: Add NDK to PATH
      run: echo "$HOME/android-ndk-r23b" >> $GITHUB_PATH

    - name: Display NDK version
      run: $HOME/android-ndk-r23b/ndk-build --version

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
        ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
        NDK_HOME: ${{ env.NDK_HOME }}
